"""Prefix Trie with per-node cached top-K completions.

This is the in-memory index that turns "give me suggestions for prefix p" into
an O(len(p)) lookup instead of an O(N) scan of 120k queries.

Design
------
A naive Trie answers "which queries start with p?" but then you still have to
sort potentially tens of thousands of matches on every keystroke (think prefix
"a"). Instead, **every node caches the top-K completions in its subtree**,
ordered by count. A lookup walks to the prefix node and returns its cached list
directly — no subtree traversal, no per-request sort.

This works cleanly here because **counts only ever increase** (a search can only
add to a query's count). Monotonic counts make incremental maintenance simple:

* On insert/update of query q with count c, we walk q's path from the root and
  *offer* (c, q) to every node along the way. Each node keeps only its best K.
* Because counts never decrease, a query already in a node's top-K only needs its
  count bumped; one that wasn't can only newly *enter* the top-K, never silently
  need eviction of itself.

K (``node_cap``) is kept a bit larger than the 10 we return so the recency
re-ranker (see ``ranking.py``) has a candidate pool to reorder. This makes the
documented trade-off explicit: candidates are generated by all-time popularity,
then reordered by recency. A cold, low-count query that suddenly spikes is
surfaced via the global Trending list rather than deep prefix suggestions.

Thread-safety: a single lock guards all mutation/read of the shared structure.
Lookups copy out a small list (<= K) under the lock and return; critical
sections are tiny.
"""

from __future__ import annotations

import threading
from typing import Dict, List, Optional, Tuple


class _Node:
    __slots__ = ("children", "top")

    def __init__(self) -> None:
        self.children: Dict[str, "_Node"] = {}
        # Cached best completions in this subtree: list of (count, query),
        # sorted by count descending, length <= cap.
        self.top: List[Tuple[int, str]] = []


class SuggestionTrie:
    def __init__(self, node_cap: int = 25) -> None:
        self.node_cap = node_cap
        self._root = _Node()
        self._lock = threading.RLock()
        self.size = 0  # number of distinct queries indexed

    # --- internal ----------------------------------------------------------
    def _offer(self, node: "_Node", count: int, query: str) -> None:
        """Insert/update (count, query) into a node's capped top list."""
        top = node.top
        # If the query is already present, update its count in place.
        for i, (_, q) in enumerate(top):
            if q == query:
                top[i] = (count, query)
                top.sort(key=lambda t: t[0], reverse=True)
                return
        # Not present. Add it if there is room or it beats the current minimum.
        if len(top) < self.node_cap:
            top.append((count, query))
            top.sort(key=lambda t: t[0], reverse=True)
        elif count > top[-1][0]:
            top[-1] = (count, query)
            top.sort(key=lambda t: t[0], reverse=True)

    def _walk_offer(self, query: str, count: int) -> None:
        node = self._root
        # The empty-prefix root also holds global top-K (handy, harmless).
        self._offer(node, count, query)
        for ch in query:
            nxt = node.children.get(ch)
            if nxt is None:
                nxt = _Node()
                node.children[ch] = nxt
            node = nxt
            self._offer(node, count, query)

    # --- public API --------------------------------------------------------
    def insert(self, query: str, count: int) -> None:
        """Index a brand-new query (or refresh an existing one)."""
        with self._lock:
            existed = self._find(query) is not None
            self._walk_offer(query, count)
            if not existed:
                self.size += 1

    def bulk_insert(self, pairs) -> None:
        """Index many (query, count) pairs efficiently at startup."""
        with self._lock:
            for query, count in pairs:
                self._walk_offer(query, count)
                self.size += 1

    def update(self, query: str, new_count: int) -> None:
        """Update an existing query's count (monotonic increase)."""
        with self._lock:
            self._walk_offer(query, new_count)

    def _find(self, query: str) -> Optional["_Node"]:
        node = self._root
        for ch in query:
            node = node.children.get(ch)
            if node is None:
                return None
        return node

    def top_for_prefix(self, prefix: str, k: int) -> List[Tuple[str, int]]:
        """Return up to ``k`` best (query, count) completions for ``prefix``."""
        with self._lock:
            node = self._find(prefix)
            if node is None:
                return []
            # node.top is (count, query); return (query, count) for callers.
            return [(q, c) for (c, q) in node.top[:k]]

    def candidates_for_prefix(self, prefix: str) -> List[Tuple[str, int]]:
        """Return the full cached candidate pool (up to node_cap) for re-ranking."""
        with self._lock:
            node = self._find(prefix)
            if node is None:
                return []
            return [(q, c) for (c, q) in node.top]
